default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@localhost:5432/furukawa_api_development" } %>

development:
  <<: *default

test:
  <<: *default
  database: furukawa_api_test

production:
  <<: *default
